spring.application.name=cursos-service
server.port=8002
spring.datasource.url=jdbc:postgresql://localhost:5432/cursos_service_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.generate-ddl=true
logging.level.org.hibernate.SQL=debug