spring.application.name=usuarios-service
server.port=8001
spring.datasource.url=jdbc:mysql://localhost:3306/usuarios_service_db
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.generate-ddl=true
logging.level.org.hibernate.SQL=debug